sudo: required

language: generic

services:
  - docker

#before_install:
#  - docker build -t galm18/react-test -f ./client/Dockerfile.dev ./client

#script:
#  - docker run -e CI=true galm18/react-test npm test

after_success:
  - docker build -t galm18/multi-client ./client
  - docker build -t galm18/multi-nginx ./nginx
  - docker build -t galm18/multi-server ./server
  - docker build -t galm18/multi-worker ./worker

#add username and password to login, and login in 1 command (encrypted in our Travis, so they're not exposed):

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#take images and push to docker hub

  - docker push galm18/multi-client
  - docker push galm18/multi-nginx
  - docker push galm18/multi-server
  - docker push galm18/multi-worker